[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

remappings = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/"
]

[rpc_endpoints]
sepolia = "${ALCHEMY_SEPOLIA_API_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_SEPOLIA_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }

[fuzz]
runs = 256
depth = 15
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

